### PR TITLE
Header

### PR DESCRIPTION
**Pull request by HeloiseFerla**
Header component with SearchBar and Favorites

### CODE REVIEW

**Review by Hacene010 — APPROVED** [review]
It looks ok for me. 
Maybe pay attention to the use of "div" tag everywhere ;)

**Review by Hacene010 — CHANGES_REQUESTED** [review]
You must read the PR by an SM before you assign me :).

**Review by Morel-Victor — APPROVED** [review]
It's ok no problem on the code for me, can be remove the divs in the Header css ?

**Review by Hacene010 — APPROVED** [review]
It's ok ;)

**Pull request merged**
